### ISSUE TITLE
Add `remove_many` method

### ISSUE THREAD

**Issue by ISibboI** [jonhoo/hashbag#13]
There is currently an `insert_many` method, but no batch method for removing.

**Comment by jonhoo** [comment]
That'd be a good thing to add, I agree! Happy to take a look at a PR :)

**Comment by TylerBloom** [comment]
This was addressed in #15.

**Comment by jonhoo** [comment]
(and released in 0.1.10)

**Comment by ISibboI** [comment]
Great, thanks!
